## Numpy Samples

In [1]:
import numpy as np

In [2]:
x=np.float32(1.0)

In [3]:
x

1.0

In [4]:
y = np.int_([1,2,4])
y

array([1, 2, 4])

In [5]:
z= np.arange(3, dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

In [6]:
print(z)

[0 1 2]


In [7]:
b=np.arange(9).reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
print[2]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [10]:
b[2]

array([6, 7, 8])

In [11]:
b[0,2]

2

In [12]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x[2:5]

array([2, 3, 4])

In [14]:
x[:-7]

array([0, 1, 2])

In [16]:
a=np.arange(5)
b=np.arange(5)
print(a)
print(b)

[0 1 2 3 4]
[0 1 2 3 4]


In [17]:
a+b

array([0, 2, 4, 6, 8])

In [18]:
a-b

array([0, 0, 0, 0, 0])

In [19]:
a**2

array([ 0,  1,  4,  9, 16], dtype=int32)

In [20]:
a>3

array([False, False, False, False,  True])

In [21]:
10*np.sin(a)

array([ 0.        ,  8.41470985,  9.09297427,  1.41120008, -7.56802495])

In [22]:
np.dot(a,b)

30

In [26]:
a=np.random.random((2,3))
a

array([[0.91511739, 0.35018181, 0.0186271 ],
       [0.0387466 , 0.86021261, 0.33203464]])

In [27]:
a.sum()

2.5149201445775047

In [28]:
a.min()

0.018627100065139457

In [29]:
a.max()

0.9151173920844629

In [30]:
a.max(axis=0)

array([0.91511739, 0.86021261, 0.33203464])

In [31]:
a.max(axis=1)

array([0.91511739, 0.86021261])

In [33]:
a=np.floor(10*np.random.random((3,4)))
print(a)
a

[[3. 6. 7. 2.]
 [0. 4. 4. 1.]
 [4. 3. 5. 9.]]


array([[3., 6., 7., 2.],
       [0., 4., 4., 1.],
       [4., 3., 5., 9.]])

In [34]:
a.shape

(3, 4)

In [35]:
a.shape = (6,2)
a

array([[3., 6.],
       [7., 2.],
       [0., 4.],
       [4., 1.],
       [4., 3.],
       [5., 9.]])

In [37]:
a.transpose()

array([[3., 7., 0., 4., 4., 5.],
       [6., 2., 4., 1., 3., 9.]])

In [39]:
from numpy.linalg import *

In [43]:
a=10*np.random.random((2,2))
a

array([[4.68912596, 1.99878007],
       [8.5663995 , 5.2129162 ]])

In [44]:
inv(a)

array([[ 0.71198439, -0.27299503],
       [-1.1700059 ,  0.64044469]])